version: '3'

services:
  postgres:
    image: postgres
    hostname: postgreshostname
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dirane
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=sergesdirane@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=dirane
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  postgres-data:
  pgadmin-data:
